# Theory of Complex Vector Spaces
Complex vector spaces extend the idea of real vector spaces by allowing vectors to have complex numbers as their components. In these spaces, vectors can be added together and multiplied by complex scalars to produce new vectors. Key operations in complex vector spaces include vector addition, scalar multiplication, vector negation, and complex conjugation.

# Processing Complex Vectors using NumPy
This section demonstrates the usage of NumPy for processing complex vectors. We'll cover basic operations like sum, negation, and multiplication by a complex scalar.

In [ ]:
import numpy as np

## Creating Complex Vectors
First, let's create some complex vectors to work with.

In [ ]:
# Creating two complex vectors
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5-1j, -2+3j])

# Displaying the vectors
v1, v2

## Sum of Complex Vectors
We can add two complex vectors using the `+` operator.

In [ ]:
# Sum of the vectors
sum_v = v1 + v2
sum_v

## Negation of a Complex Vector
Negating a complex vector is straightforward with the `-` operator.

In [ ]:
# Negation of v1
neg_v1 = -v1
neg_v1

## Multiplication by a Complex Scalar
Multiplying a complex vector by a complex scalar involves element-wise multiplication.

In [ ]:
# Multiplying v1 by a complex scalar
scalar = 2 - 1j
mult_v1 = scalar * v1
mult_v1

This notebook provides a basic overview of handling complex vectors using NumPy. For more advanced operations and functions, NumPy's extensive documentation and community resources can be consulted.

## More operations with vectors: Conjugate, Transpose, Adjunct
Here we demonstrate how to manipulate complex column vectors using NumPy, including operations like sum, negation, multiplication by a scalar, transpose, adjunct, and conjugate.

In [ ]:

import numpy as np

# Define two complex column vectors
v1 = np.array([[2+3j], [5-4j], [1+1j]])
v2 = np.array([[1-1j], [3+2j], [4-4j]])

# Sum
sum_v = v1 + v2

# Negation
neg_v1 = -v1

# Multiplication by a scalar
scalar = 2 + 1j
mult_v1 = v1 * scalar

# Transpose
transpose_v1 = v1.T

# Adjunct (Conjugate transpose)
adjunct_v1 = v1.T.conj()

# Conjugate
conjugate_v1 = np.conjugate(v1)

(sum_v, neg_v1, mult_v1, transpose_v1, adjunct_v1, conjugate_v1)


# Theory of Vector Spaces using Matrices
In the context of matrices, vector spaces can be defined where each vector is a matrix of a particular size. Operations on these matrix-vector spaces include matrix addition, scalar multiplication, matrix negation, transpose, adjunct, and conjugate. In this section, we focus on square matrices of size 3x3.

## Manipulating Square Matrices using NumPy
Examples of how to manipulate 3x3 square matrices using NumPy, showing operations such as sum, negation, multiplication by a scalar, conjugate, transpose, and adjunct.

In [ ]:

# Define two 3x3 complex matrices
m1 = np.array([[2+3j, 4-1j, 0], 
               [1+1j, 3+3j, 5], 
               [4, 6-2j, 1-1j]])
m2 = np.array([[1, 2+1j, 3-3j], 
               [0, -1+2j, 1-2j], 
               [3+3j, 2, 4+4j]])

# Sum
sum_m = m1 + m2

# Negation
neg_m1 = -m1

# Multiplication by a scalar
scalar = 0.5 + 0.5j
mult_m1 = m1 * scalar

# Conjugate
conjugate_m1 = np.conjugate(m1)

# Transpose
transpose_m1 = m1.T

# Adjunct (Conjugate transpose)
adjunct_m1 = m1.T.conj()

(sum_m, neg_m1, mult_m1, conjugate_m1, transpose_m1, adjunct_m1)


## Checking the Dimension of a Matrix
We can check the dimension of a matrix using the `.shape` attribute.

In [ ]:
# Checking the dimension of matrix1
m1.shape

## Action of a Matrix on a Vector
Finally, examples of how to use Python to multiply a 3x3 square matrix by a 3x1 column vector.

In [ ]:

# Multiplying a 3x3 matrix by a 3x1 vector
result = np.dot(m1, v1)
result


# Processing Complex Vectors using NumPy
This notebook demonstrates the usage of NumPy for processing complex vectors. We'll cover basic operations like sum, negation, and multiplication by a complex scalar.

# Exercises on Complex Vectors and Matrices

This set of exercises focuses on operations with complex column vectors and complex square matrices, including concrete cases with vectors and matrices written in LaTeX format.

## Complex Column Vector Operations

### Exercise 1: Sum of Two Complex Vectors
Given two complex vectors 
$$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $$ 
and 
$$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $$, 
find their sum.

### Exercise 2: Negation of a Complex Vector
Given a complex vector 
$$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $$, 
find its negation.

### Exercise 3: Multiplication of a Complex Vector by a Scalar
Multiply the complex vector 
$$ v = \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} $$ 
by the complex scalar $$ 3 + i $$.

### Exercise 4: Transpose of a Complex Vector
Find the transpose of the complex vector 
$$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $$.

### Exercise 5: Conjugate of a Complex Vector
Compute the conjugate of the complex vector 
$$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $$.

### Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector
Find the adjunct (or conjugate transpose) of the complex vector 
$$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $$.

## Complex Square Matrix Operations

### Exercise 7: Sum of Two Complex Matrices
Given two complex matrices 
$$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $$ 
and 
$$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $$, 
calculate their sum.

### Exercise 8: Negation of a Complex Matrix
Find the negation of the complex matrix 
$$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $$.

### Exercise 9: Multiplication of a Complex Matrix by a Scalar
Multiply the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $$ 
by the complex scalar $$ 2 + 3i $$.

### Exercise 10: Conjugate of a Complex Matrix
Compute the conjugate of the complex matrix 
$$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $$.

### Exercise 11: Transpose of a Complex Matrix
Find the transpose of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $$.

### Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix
Calculate the adjunct (or conjugate transpose) of the complex matrix 
$$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $$.

### Exercise 13: Checking the Dimensions of a Matrix
Determine the dimensions of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $$.

## Multiplication of Matrices and Vectors

### Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector
Multiply the complex square matrix 
$$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $$ 
by the complex column vector 
$$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $$.

## Instructions
For each exercise, ensure to display both the input (vectors/matrices) and the result of the operation.Use NumPy for these exercises to practice handling complex numbers and matrix operations in Python.

## Actividad
## Estudiante Laura Valentina Rodríguez Ortegón

In [12]:
import numpy as np

#Punto 1
#Para la adición de vectores complejos 
def adiveccplx (a,b):
    result = a + b  # Suma directa usando la funcionalidad de NumPy
    vector1 = result[:2, :2]  # Extrae el primer vector de 2x2
    vector2 = result[2:, 2:]
    return (vector1, vector2)
    
#Punto 2 
#Negación de los vectores complejos
def negacionveccplx (v):
    negacion_v = -v
    return (negacion_v)

#Punto 3
#Multiplicacion de un vector complejo y un escalar
def multvectyesccplx (v3, escalar):
    resmulvecyesc = v3 * escalar
    return (resmulvecyesc)
    
#Punto 4 
#Transpuesta de una vector 
def transmatrcplx (c):
    x=np.array(c)
    y=np.transpose(x)
    return (y)

#Punto 5
#Conjugada de un vector
def conjumatcplx (d):
    m = np.matrix(d) 
    nueva = np.conj(m) 
    return (nueva)

#Punto 6
#Adjunta de un vector
def adjmatcplx (e):
    return ([(e[1][1]),((-1)*(e[0][1]))],[((-1)*(e[1][0])),(e[0][0])])

#Punto 7
#La adición de matrices complejas 
def adimatcplx (m1,m2):
    if len(a) != len(b) or len(a[0]) != len(b[0]):
        raise ValueError("Las matrices deben tener la misma dimensión")
    suma = [[0 for i in range(len(m1[0]))] for j in range(len(m1))]
    for i in range(len(m1)):
        for j in range(len(m1[0])):
          suma[i][j] = m1[i][j] + m2[i][j]
    return suma

#Punto 8
#Negacion de matriz compleja
def negmatcplx (matrix):
    negacion = [[0 for i in range(len(matrix[0]))] for j in range(len(matrix))]
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            negacion[i][j] = -matrix[i][j]
    return negacion

#Punto 9
#La multiplicación de un escalar por una matriz compleja
def multiescapormatrcplx(h, i):
    n = complex(h[0], h[1])
    m = n.imag
    fila1 = np.array([(n*i[0][0][0] - m*i[0][0][1]), (n*i[0][0][1] + m*i[0][0][0])])
    fila2 = np.array([(n*i[0][1][0] - m*i[0][1][1]), (n*i[0][1][1] + m*i[0][1][0])])
    nueva = np.array([fila1, fila2])
    return nueva

#Punto 10
#Conjugada de una matriz/vector
def conjumatcplx (d):
    m = np.matrix(d) 
    nueva = np.conj(m) 
    return (nueva)

#Punto 11
#Transpuesta de una matriz 
def transmatrcplx (c):
    x=np.array(c)
    y=np.transpose(x)
    return (y)
    
#Punto 12
#Adjunta de una matriz
def adjmatcplx (e):
    return [[e[1][1], (-1) * e[0][1]], [(-1) * e[1][0], e[0][0]]]

#Punto 13
#Chequear las dimensiones de la matriz compleja 
def dimenmatcplx(m):
    return (m.shape)

#Punto 14
#Calcular la multiplicación de una matriz sobre un vector
def accimatrizsobrevectcplx (v,w):
    n = v[0][0]
    m = v[1][0]
    fila1 = (n * w[0][0][0] - m * w[0][0][1],
               n * w[0][0][1] + w[0][0][0] * m)
    fila1b = (n * w[0][1][0] - m * w[0][1][1],
                n * w[0][1][1] + w[0][1][0] * m)
    fila2 = (n * w[1][0][0] - m * w[1][0][1],
               n * w[1][0][1] + w[1][0][0] * m)
    fila2b = (n * w[1][1][0] - m * w[1][1][1],
                n * w[1][1][1] + w[1][1][0] * m)
    nueva = [[fila1, fila1b], [fila2, fila2b]]
    return nueva

if __name__ == '__main__':
    #Punto (1)
    #La suma de vectores complejos
    a = np.array([[1+2j], [3-1j]], dtype=complex)
    b = np.array([[2-1j], [4+2j]], dtype=complex)
    vector1, vector2 = adiveccplx(a, b)
    print ("Adiciones de vectores complejos: \n")
    print(vector1)
    print(vector2)
    print ()

    #Punto (2) 
    #La negación de vectores complejos
    v = np.array([[2 + 3j], [1 - 2j]], dtype=complex)
    print("La negación del vector complejo es: \n", negacionveccplx (v))
    print()

    #Punto (3)
    #Multiplicación de un vector complejo y un escalar
    v3 = np.array([[1 - 1j], [2 + 2j]], dtype=complex)
    escalar = 3 + 1j
    print("La multiplicación del vector complejo y el escalar es: \n", multvectyesccplx (v3, escalar))
    print ()
    
    #Punto (4)
    #La transpuesta de un vector 
    c=[[2,-1],[3,4]]
    print ("La transpuesta del vector complejo es: \n",(transmatrcplx(c)))
    print ()

    #Punto (5)
    #Conjugada de un vector
    d= (((1 + 1j), (2 -3j))) #Donde j es el número imaginario que va quedar * por (-1)
    print ("La conjugada del vector complejo es: \n",(conjumatcplx(d)))
    print ()

    #Punto (6)
    #La adjunta de un vector
    e= [[1,-2],[3,1]]
    print ("La adjunta del vector complejo es: \n",(adjmatcplx(e)))
    print()
    
    #Punto (7)
    #Adición de matrices complejas
    m1 = [[1, 1],[2, -1],[3 , 2],[4 , 0]]
    m2 = [[2, -3],[1, 0],[0 , 1],[2 , 2]]
    print ("La adición de las matrices complejas: \n",adimatcplx(m1,m2))
    print ()

    #Punto (8)
    #Negación de una matriz compleja
    matrix = [[2,1],[3,0],[1,-1],[2,2]]
    print ("La negación de una matriz compleja es: \n",negmatcplx(matrix))
    print ()

    #Punto (9)
    #La multiplicación de un escalar por un matriz
    h= (2 , 3)
    i= [[[1 , -1], [2 , 0]],[[3 , 1], [4 , -2]]]
    print ("La multiplicación del escalar por una matriz es: \n",multiescapormatrcplx(h,i))#Multiplicación de un escalar por una matriz
    print ()

    #Punto (10)
    #Conjugada de una matriz
    d= (((1 + 1j), (2 + 0j), (3-1j), (4+2j)))#Donde j es el número imaginario que va quedar * por (-1)
    print ("La conjugada de una matriz: \n",(conjumatcplx(d)))
    print ()

    #Punto (11)
    #La transpuesta de la matriz 
    c=[[[1,-1],[2 , 2]],[[3 , 0],[4 , -1]]]
    print ("La transpuesta de una matriz: \n",(transmatrcplx(c)))
    print ()

    #Punto (12)
    #La adjunta de una matriz
    e = [[1, 2], [2, -1], [4, 0], [5, 1]]
    print ("La adjunta de una matriz: \n",(adjmatcplx(e)))
    print()

    #Punto (13)
    #Chequear las dimensiones de la matriz compleja 
    m = np.array([[1, -1], [2, 0], [3, 2], [4, -1]])
    print ("Las dimensiones de una matriz: \n",(dimenmatcplx(m)))
    print()

    #Punto (14)
    #Calcular la acción de una matriz sobre un vector
    v = [[2,-1],[1 , 3]]
    w = ([[1 , 1],[2 , -1]],[[3 , 0],[4 , 1]])
    print ("la acción de una matriz sobre un vector: \n",accimatrizsobrevectcplx(v,w))#la acción de una matriz sobre un vector
    print ()

Adiciones de vectores complejos: 

[[3.+1.j]
 [7.+1.j]]
[]

La negación del vector complejo es: 
 [[-2.-3.j]
 [-1.+2.j]]

La multiplicación del vector complejo y el escalar es: 
 [[4.-2.j]
 [4.+8.j]]

La transpuesta del vector complejo es: 
 [[ 2  3]
 [-1  4]]

La conjugada del vector complejo es: 
 [[1.-1.j 2.+3.j]]

La adjunta del vector complejo es: 
 [[1, 2], [-3, 1]]

La adición de las matrices complejas: 
 [[3, -2], [3, -1], [3, 3], [6, 2]]

La negación de una matriz compleja es: 
 [[-2, -1], [-3, 0], [-1, 1], [-2, -2]]

La multiplicación del escalar por una matriz es: 
 [[5.+3.j 1.-3.j]
 [4.+6.j 6.+0.j]]

La conjugada de una matriz: 
 [[1.-1.j 2.-0.j 3.+1.j 4.-2.j]]

La transpuesta de una matriz: 
 [[[ 1  3]
  [ 2  4]]

 [[-1  0]
  [ 2 -1]]]

La adjunta de una matriz: 
 [[-1, -2], [-2, 1]]

Las dimensiones de una matriz: 
 (4, 2)

la acción de una matriz sobre un vector: 
 [[(1, 3), (5, 0)], [(6, 3), (7, 6)]]

